
# 
# Available model_name to choose from: bert-base-uncased, roberta-base, microsoft/deberta-base
# 
model_name: 'microsoft/deberta-base'
seed: 42
sampling_random_state: 42
batch_size: 8
learning_rate: 5e-2
